"""Markdown report generator."""
from __future__ import annotations

import logging

from ..schemas.report import TrustReport

logger = logging.getLogger(__name__)

_GRADE_THRESHOLDS = [(90, "A"), (75, "B"), (60, "C"), (45, "D"), (0, "F")]


def _grade(score: int) -> str:
    for threshold, grade in _GRADE_THRESHOLDS:
        if score >= threshold:
            return grade
    return "F"


def _bar(value: int, width: int = 20) -> str:
    filled = int(value / 100 * width)
    return "█" * filled + "░" * (width - filled)


def render(report: TrustReport) -> str:
    """Render a TrustReport as a Markdown string."""
    lines: list[str] = []
    grade = _grade(report.composite_score)

    lines += [
        f"# Agent Trust Report — {report.agent_name}",
        "",
        f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**SDK Version:** {report.sdk_version}  ",
        f"**Traces Evaluated:** {report.trace_count}",
        "",
        "---",
        "",
        "## Overall Trust Score",
        "",
        f"```",
        f"  {report.composite_score:3d} / 100   Grade: {grade}",
        f"  {_bar(report.composite_score)}",
        f"```",
        "",
    ]

    if report.trace_context:
        ctx = report.trace_context
        lines += ["## Trace Context", "", "| Field | Value |", "|-------|-------|"]
        if ctx.get("models"):
            lines.append(f"| Model(s) | {', '.join(ctx['models'])} |")
        if "avg_temperature" in ctx:
            lines.append(
                f"| Temperature (avg / min / max) | "
                f"{ctx['avg_temperature']} / {ctx['min_temperature']} / {ctx['max_temperature']} |"
            )
        if "avg_conversation_turns" in ctx:
            lines.append(f"| Avg conversation turns | {ctx['avg_conversation_turns']} |")
        if ctx.get("finish_reasons"):
            lines.append(f"| Finish reason(s) | {', '.join(ctx['finish_reasons'])} |")
        lines.append(f"| Traces with tools defined | {ctx.get('traces_with_tools_defined', 0)} |")
        lines.append("")

    if report.warnings:
        lines += ["## ⚠ Warnings", ""]
        for w in report.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines += ["## Dimension Scores", ""]
    lines += [
        "| Dimension | Score | Bar |",
        "|-----------|------:|-----|",
    ]
    for dim in report.dimension_scores:
        lines.append(f"| {dim.dimension} | {dim.value:3d} | {_bar(dim.value, 10)} |")

    lines += ["", "---", ""]

    for dim in report.dimension_scores:
        lines += [
            f"## {dim.dimension} — {dim.value}/100",
            "",
            f"*{dim.explanation}*",
            "",
            "| Test | Score | Pass | Reason |",
            "|------|------:|:----:|--------|",
        ]
        for gr in dim.guardrail_results:
            passed_icon = "✓" if gr.passed else "✗"
            lines.append(
                f"| `{gr.test_name}` | {gr.score:.2f} | {passed_icon} | {gr.reason} |"
            )
        lines.append("")

    lines += [
        "---",
        "",
        f"*{report.summary}*",
        "",
        f"*Generated by agent-trust v{report.sdk_version}*",
    ]

    return "\n".join(lines)


def write(report: TrustReport, path: str) -> None:
    """Write a rendered Markdown report to a file."""
    content = render(report)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info("Markdown report written to %s", path)
